@host=http://localhost:3000/api/v1/chat



POST {{host}}
Content-Type: application/json
Authorization: Bearer <your valid jwt token>

{
  "chatId" : "67a0cf0e1e6a91eb3dc337c1",
  "aiModel": "qwen2:0.5b",


  "contents" : [
    {"content": "1+1", "role": "user", "_id":"67a0cf0e1e6a91eb3dc337c2", "date": "2025-02-03T14:13:34.519Z"},
    {"content": "1 + 1 = 2", "role": "assistant", "_id": "67a0cf0e1e6a91eb3dc337c3", "date": "2025-02-03T14:13:34.520Z"},
    {"content" :  "ADD 3 to your precedent response", "role" :  "user"}
  ]
}



###

GET {{host}}/history
Authorization: Bearer <your valid jwt token>